version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.18.0
    - 4.19.0
    - 4.20.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.34
    - 14.14.35
  - dependency-name: eslint
    versions:
    - 7.22.0
  - dependency-name: next
    versions:
    - 10.0.8
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.8
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.17.0
